// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNCKH_HocVien.Data;

#nullable disable

namespace QLNCKH_HocVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212054848_AddAuthAndIndexes")]
    partial class AddAuthAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.ChuyenDeNCKH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHocVien")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdLinhVuc")
                        .HasColumnType("int");

                    b.Property<string>("MaSoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChuyenDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaSoCD")
                        .IsUnique();

                    b.ToTable("ChuyenDeNCKHs");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("float");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCapBac")
                        .HasColumnType("int");

                    b.Property<int?>("IdChucDanh")
                        .HasColumnType("int");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("IdDonViCongTac")
                        .HasColumnType("int");

                    b.Property<int?>("IdHocHam")
                        .HasColumnType("int");

                    b.Property<int?>("IdHocVi")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTonGiao")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrinhDoChuyenMon")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrinhDoLLCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("LinhVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaSoCB")
                        .IsUnique();

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.HoiDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChuyenDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCham")
                        .HasColumnType("datetime2");

                    b.Property<int>("VongThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HoiDongs");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.KetQuaSoLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DiemSo")
                        .HasColumnType("float");

                    b.Property<int>("IdChuyenDe")
                        .HasColumnType("int");

                    b.Property<bool>("KetQua")
                        .HasColumnType("bit");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KetQuaSoLoais");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Quản trị viên",
                            IsActive = true,
                            MatKhau = "o8dJmVSf+0e3kEpbSfbF0DP3lmfKGTG8FhCXJ0kbJbY=",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.NopSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChuyenDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NopSanPhams");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.PhieuCham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<int>("IdChuyenDe")
                        .HasColumnType("int");

                    b.Property<int>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<string>("YKien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhieuChams");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNganh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTonGiao")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaSV")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.ThanhVienHoiDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<int>("IdHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHoiDong");

                    b.ToTable("ThanhVienHoiDongs");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.XepGiai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DiemTrungBinh")
                        .HasColumnType("float");

                    b.Property<int>("IdChuyenDe")
                        .HasColumnType("int");

                    b.Property<string>("TenGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("XepGiais");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.ThanhVienHoiDong", b =>
                {
                    b.HasOne("QLNCKH_HocVien.Client.Models.HoiDong", null)
                        .WithMany("ThanhViens")
                        .HasForeignKey("IdHoiDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.HoiDong", b =>
                {
                    b.Navigation("ThanhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
