// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNCKH_HocVien.Data;

#nullable disable

namespace QLNCKH_HocVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201172219_TaoBangChuyenDe")]
    partial class TaoBangChuyenDe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.ChuyenDeNCKH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHocVien")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdLinhVuc")
                        .HasColumnType("int");

                    b.Property<string>("MaSoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenDeNCKHs");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("float");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCapBac")
                        .HasColumnType("int");

                    b.Property<int?>("IdChucDanh")
                        .HasColumnType("int");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("IdDonViCongTac")
                        .HasColumnType("int");

                    b.Property<int?>("IdHocHam")
                        .HasColumnType("int");

                    b.Property<int?>("IdHocVi")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTonGiao")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrinhDoChuyenMon")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrinhDoLLCT")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("LinhVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("QLNCKH_HocVien.Client.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNganh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdTonGiao")
                        .HasColumnType("int");

                    b.Property<int?>("IdXa")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
